# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4722b8e6eb232c6d1db1866c5d4fc65ed6c0c6cc564b62761fc08a25dc488ca1ee5d6f9522ea108a36453873ed3f63d17004c46114c7ea46c1ed2ed044fa039f

test:
  secret_key_base: b76fa9dec0eed44abdc17948507377184bcdb7819bd0b03c74ce88c75f08e0cb118b5e56cc89fdbc9467e42d9da95024934552c93077c78426d2db254e1838c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
